- name: Checkout repository
  uses: actions/checkout@v3

- name: Set up SSH connection
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.AZURE_VM_IP }}
    username: azureuser
    key: ${{ secrets.AZURE_SSH_KEY }}
    script: |
      cd /var/www/app || mkdir -p /var/www/app && cd /var/www/app
      git clone https://github.com/NorAjami/SecureCloudApp.git || git pull origin main
      dotnet publish -c Release -o out
      sudo systemctl restart myapp
